/*
 * Test-only DLL (not shipped): the ahead-of-time compiled application program
 * and the test program corpus, the emergency guard, the lease, shared memory,
 * the frame parser and the session, exposed to the C# test suite.
 */
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../common/bfrt.h"

typedef int (__stdcall *test_read_fn)(void);
typedef int (__stdcall *test_write_fn)(int value);

/* Generated by tools/BfAot from the corpus the tests write (test.ps1). */
extern const bf_named_program bf_test_programs[];

/* Resolves a program by name: "g29" is the application program, anything else
   an entry of the test corpus. NULL when unknown. */
__declspec(dllexport) bf_program_fn __stdcall bft_program(const char *name)
{
    const bf_named_program *entry;
    if (strcmp(name, "g29") == 0) {
        return g29_program_run;
    }

    for (entry = bf_test_programs; entry->name; entry++) {
        if (strcmp(entry->name, name) == 0) {
            return entry->run;
        }
    }

    return NULL;
}

/*
 * A compiled program the C# harness can drive like the reference interpreter:
 * bft_run returns BF_STOPPED when the program asks for input the harness does
 * not have yet, and the next bft_run continues from that read. Compiled code
 * cannot return from the middle of a read, so the program runs on its own
 * thread and control is handed back and forth; exactly one side runs at a time.
 */
typedef struct {
    bf_context context;
    bf_program_fn program;
    test_read_fn read;
    test_write_fn write;
    HANDLE thread;
    HANDLE resume;
    HANDLE yielded;
    volatile LONG closing;
    int status;
    int ended;
} test_machine;

static int machine_read(void *io)
{
    test_machine *machine = (test_machine *)io;
    for (;;) {
        int value;
        if (machine->closing) {
            return -1;
        }

        value = machine->read();
        if (value >= 0) {
            return value;
        }

        machine->status = BF_STOPPED;
        SetEvent(machine->yielded);
        WaitForSingleObject(machine->resume, INFINITE);
    }
}

static int machine_write(void *io, unsigned char value)
{
    return ((test_machine *)io)->write(value);
}

static DWORD WINAPI machine_thread(void *argument)
{
    test_machine *machine = (test_machine *)argument;
    int result = machine->program(&machine->context);
    if (!machine->closing) {
        machine->status = result;
        machine->ended = 1;
        SetEvent(machine->yielded);
    }

    return 0;
}

__declspec(dllexport) test_machine *__stdcall bft_create(bf_program_fn program, test_read_fn read, test_write_fn write, long long budget)
{
    test_machine *machine = (test_machine *)calloc(1, sizeof(test_machine));
    if (!machine) {
        return NULL;
    }

    machine->program = program;
    machine->read = read;
    machine->write = write;
    machine->resume = CreateEventW(NULL, FALSE, FALSE, NULL);
    machine->yielded = CreateEventW(NULL, FALSE, FALSE, NULL);
    if (!program || !machine->resume || !machine->yielded || !bf_context_init(&machine->context, machine_read, machine_write, machine, budget)) {
        if (machine->resume) {
            CloseHandle(machine->resume);
        }

        if (machine->yielded) {
            CloseHandle(machine->yielded);
        }

        free(machine);
        return NULL;
    }

    return machine;
}

/* 1 finished, 0 waiting for input, -1 fault (message in fault). */
__declspec(dllexport) int __stdcall bft_run(test_machine *machine, char *fault, int fault_length)
{
    if (!machine->ended) {
        if (!machine->thread) {
            machine->thread = CreateThread(NULL, 256 * 1024, machine_thread, machine, STACK_SIZE_PARAM_IS_A_RESERVATION, NULL);
            if (!machine->thread) {
                snprintf(fault, (size_t)fault_length, "The program thread could not be created.");
                return BF_FAULT;
            }
        } else {
            SetEvent(machine->resume);
        }

        WaitForSingleObject(machine->yielded, INFINITE);
    }

    if (machine->status == BF_FAULT) {
        snprintf(fault, (size_t)fault_length, "%s", machine->context.fault);
    }

    return machine->status;
}

__declspec(dllexport) long long __stdcall bft_total_iterations(test_machine *machine)
{
    return bf_context_iterations(&machine->context);
}

__declspec(dllexport) long long __stdcall bft_peak_iterations(test_machine *machine)
{
    return machine->context.peak;
}

__declspec(dllexport) void __stdcall bft_set_cell(test_machine *machine, int index, int value)
{
    if ((unsigned int)index < BF_TAPE_LENGTH) {
        machine->context.tape[index] = value;
    }
}

/* Reads a cell while the program waits or after it ended. */
__declspec(dllexport) int __stdcall bft_cell(test_machine *machine, int index)
{
    return (unsigned int)index < BF_TAPE_LENGTH ? machine->context.tape[index] : 0;
}

__declspec(dllexport) void __stdcall bft_free(test_machine *machine)
{
    if (!machine) {
        return;
    }

    if (machine->thread) {
        if (!machine->ended) {
            InterlockedExchange(&machine->closing, 1);
            SetEvent(machine->resume);
        }

        WaitForSingleObject(machine->thread, INFINITE);
        CloseHandle(machine->thread);
    }

    CloseHandle(machine->resume);
    CloseHandle(machine->yielded);
    bf_context_free(&machine->context);
    free(machine);
}

typedef struct {
    const uint8_t *input;
    int input_length;
    int position;
    uint8_t *output;
    int capacity;
    int written;
} replay_io;

static int replay_read(void *context)
{
    replay_io *io = (replay_io *)context;
    return io->position < io->input_length ? io->input[io->position++] : -1;
}

static int replay_write(void *context, unsigned char value)
{
    replay_io *io = (replay_io *)context;
    if (io->written >= io->capacity) {
        return 1;
    }

    io->output[io->written++] = value;
    return 0;
}

/* Benchmark: runs a fresh instance of the application program over a recorded
   input stream on the calling thread, without any managed callback. Returns
   the run result; *written receives the output length. */
__declspec(dllexport) int __stdcall bft_replay(const uint8_t *input, int length, uint8_t *output, int capacity, int *written)
{
    replay_io io = { input, length, 0, output, capacity, 0 };
    bf_context context;
    int result;
    if (!bf_context_init(&context, replay_read, replay_write, &io, BF_DEFAULT_ITERATION_BUDGET)) {
        return -2;
    }

    result = g29_program_run(&context);
    bf_context_free(&context);
    *written = io.written;
    return result;
}

/* ------------------------------------------------------------------------- */
/* The emergency guard and shared memory, for BridgeTests.                    */
/* ------------------------------------------------------------------------- */

#include "../common/guard.h"
#include "../common/system.h"

typedef int (__stdcall *test_guard_writer_fn)(const wchar_t *path, int output_length, const uint8_t *payload, int length);

static int guard_writer_adapter(void *context, const wchar_t *path, int output_length, const uint8_t *payload, size_t length)
{
    return ((test_guard_writer_fn)context)(path, output_length, payload, (int)length);
}

__declspec(dllexport) output_guard *__stdcall bft_guard_create(int ceiling_percent, test_guard_writer_fn writer)
{
    output_guard *guard = guard_create(ceiling_percent);
    if (guard && writer) {
        guard_set_writer(guard, guard_writer_adapter, (void *)writer);
    }

    return guard;
}

__declspec(dllexport) int __stdcall bft_guard_check(output_guard *guard, const uint8_t *payload, int length)
{
    return guard_check(guard, payload, (size_t)length) != NULL;
}

__declspec(dllexport) void __stdcall bft_guard_written(output_guard *guard, const wchar_t *path, int output_length, const uint8_t *payload, int length)
{
    guard_written(guard, path, output_length, payload, (size_t)length);
}

__declspec(dllexport) int __stdcall bft_guard_any(output_guard *guard)
{
    return guard_any_force(guard);
}

__declspec(dllexport) void __stdcall bft_guard_stop(output_guard *guard)
{
    guard_emergency_stop(guard);
}

__declspec(dllexport) void __stdcall bft_guard_free(output_guard *guard)
{
    guard_free(guard);
}

__declspec(dllexport) shared_memory *__stdcall bft_shm_table(void)
{
    return shm_create_table();
}

__declspec(dllexport) void __stdcall bft_shm_free(shared_memory *table)
{
    shm_free_table(table);
}

__declspec(dllexport) int __stdcall bft_shm_create(shared_memory *table, const wchar_t *name, int size, int everyone, uint32_t *handle)
{
    return shm_create(table, name, (uint32_t)size, everyone, handle);
}

__declspec(dllexport) int __stdcall bft_shm_open(shared_memory *table, const wchar_t *name, int size, uint32_t *handle)
{
    return shm_open(table, name, (uint32_t)size, handle);
}

__declspec(dllexport) int __stdcall bft_shm_read(shared_memory *table, uint32_t handle, int offset, uint8_t *data, int length)
{
    return shm_read(table, handle, (uint32_t)offset, data, (size_t)length);
}

__declspec(dllexport) int __stdcall bft_shm_write(shared_memory *table, uint32_t handle, int offset, const uint8_t *data, int length)
{
    return shm_write(table, handle, (uint32_t)offset, data, (size_t)length);
}

__declspec(dllexport) void __stdcall bft_shm_close(shared_memory *table, uint32_t handle)
{
    shm_close(table, handle);
}

/* ------------------------------------------------------------------------- */
/* The native safety envelope and the ABI boundary, for SafetyTests.          */
/* ------------------------------------------------------------------------- */

#include "../common/frames.h"
#include "../common/lease.h"
#include "../common/session.h"

static uint64_t fake_now;

static uint64_t fake_clock(void)
{
    return fake_now;
}

__declspec(dllexport) void __stdcall bft_guard_fake_clock(output_guard *guard, long long now)
{
    fake_now = (uint64_t)now;
    guard_set_clock(guard, fake_clock);
}

__declspec(dllexport) int __stdcall bft_guard_lower(output_guard *guard, int ceiling_percent)
{
    return guard_lower_ceiling(guard, ceiling_percent);
}

__declspec(dllexport) void __stdcall bft_guard_trip(output_guard *guard)
{
    guard_trip(guard);
}

__declspec(dllexport) long long __stdcall bft_guard_held(output_guard *guard, long long now)
{
    return (long long)guard_force_held_ms(guard, (uint64_t)now);
}

/* 0 when the lease holds, 1 for the hold limit, 2 for a stalled program. */
__declspec(dllexport) int __stdcall bft_lease_evaluate(output_guard *guard, g29_session *session, int max_hold_ms, int stall_ms, long long now)
{
    const char *reason = lease_evaluate(guard, session, (uint32_t)max_hold_ms, (uint32_t)stall_ms, (uint64_t)now);
    if (!reason) {
        return 0;
    }

    return strstr(reason, "held longer") ? 1 : 2;
}

typedef void (__stdcall *test_expired_fn)(const char *reason);

static void expired_adapter(void *context, const char *reason)
{
    ((test_expired_fn)context)(reason);
}

__declspec(dllexport) force_lease *__stdcall bft_lease_start(output_guard *guard, g29_session *session, int max_hold_ms, int stall_ms, test_expired_fn expired)
{
    return lease_start(guard, session, (uint32_t)max_hold_ms, (uint32_t)stall_ms, expired_adapter, (void *)expired);
}

__declspec(dllexport) void __stdcall bft_lease_stop(force_lease *lease)
{
    lease_stop(lease);
}

__declspec(dllexport) int __stdcall bft_registry_writable(const wchar_t *path)
{
    return system_registry_writable(path);
}

/* Feeds bytes to a fresh command-frame parser. Answers the number of complete
   frames, or -(1 + index) of the byte that was a violation; the last frame's
   type, flags, sequence and length go to last[0..3]. */
__declspec(dllexport) int __stdcall bft_parse_frames(const uint8_t *bytes, int length, int *last)
{
    frame_parser *parser = (frame_parser *)calloc(1, sizeof(frame_parser));
    char error[256];
    int index, frames = 0;
    if (!parser) {
        return -1000000;
    }

    for (index = 0; index < length; index++) {
        int result = frame_parser_push(parser, bytes[index], error, sizeof(error));
        if (result < 0) {
            free(parser);
            return -(1 + index);
        }

        if (result == 1) {
            frames++;
            last[0] = parser->frame.type;
            last[1] = parser->frame.flags;
            last[2] = parser->frame.sequence;
            last[3] = parser->frame.length;
        }
    }

    free(parser);
    return frames;
}

/* A program session whose commands go to a test callback (which may block). */
typedef int (__stdcall *test_command_fn)(int type, int length);
typedef void (__stdcall *test_failure_fn)(const char *message);

typedef struct {
    test_command_fn command;
    test_failure_fn failure;
} test_session_callbacks;

static int session_command_adapter(void *context, const g29_frame *frame, char *error, size_t error_length)
{
    test_session_callbacks *callbacks = (test_session_callbacks *)context;
    if (callbacks->command(frame->type, frame->length) != 0) {
        snprintf(error, error_length, "refused by the test");
        return 1;
    }

    return 0;
}

static void session_failure_adapter(void *context, const char *message)
{
    ((test_session_callbacks *)context)->failure(message);
}

__declspec(dllexport) g29_session *__stdcall bft_session_create(bf_program_fn program, test_command_fn command, test_failure_fn failure, long long budget)
{
    test_session_callbacks *callbacks = (test_session_callbacks *)calloc(1, sizeof(test_session_callbacks));
    g29_session *session;
    if (!callbacks) {
        return NULL;
    }

    callbacks->command = command;
    callbacks->failure = failure;
    session = session_create(program, session_command_adapter, session_failure_adapter, callbacks, budget);
    if (!session || !session_start(session)) {
        return NULL;
    }

    return session;
}

__declspec(dllexport) void __stdcall bft_session_post(g29_session *session, int type, const uint8_t *payload, int length)
{
    session_post(session, (uint8_t)type, 0, payload, (size_t)length);
}

__declspec(dllexport) int __stdcall bft_session_stalled(g29_session *session, int milliseconds)
{
    return session_stalled(session, (unsigned long)milliseconds);
}

__declspec(dllexport) int __stdcall bft_session_failed(g29_session *session)
{
    return session_failed(session);
}

__declspec(dllexport) int __stdcall bft_session_end(g29_session *session, int milliseconds)
{
    int ended;
    session_stop(session);
    ended = session_join(session, (unsigned long)milliseconds);
    if (ended) {
        session_free(session);
    }

    return ended;
}
